on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<p>Thanks for opening an issue on this Feature/Bug. If u can Fix this Bug or add a feaure just help us by contributing. Thanks for bug/feature we will take care of this.</p>'
          pr-message: '<p>Thanks for contributing to this project. If u found any bug try to fix it and open an issue on that. Answer questions in discussions and help us to improve this project</p>'
