on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Code of conduct</h1><p>Participation in this is governed by the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).</p><h1> Thank you </h1><p> we appreciate your create an issue to our website and our documentation!<p>'
          pr-message: '<h1> Code of conduct </h1><p>Participation in this is governed by the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).</p><h1>Thank you</h1><p> we appreciate your contributions to our website and our documentation!</p>'
